### ISSUE TITLE
Minor Issues (Ongoing)

### ISSUE THREAD

**Issue by LTenhet** [Mortikus/TLJNWN#9]
(Leave for Update)

**Comment by LTenhet** [comment]
Fix Coruscant Temple transitions

**Comment by LTenhet** [comment]
Put Ammo merchant on every planet

**Comment by LTenhet** [comment]
Fix the Phoenix Transition (uses incorrect keys)
Transition between two halves of the Phoenix broke
Vanilla loot in crates (Crates should be unusable)

**Comment by LTenhet** [comment]
Update Rules in Welcome Area

**Comment by LTenhet** [comment]
Dual Sabers can be dual wielded with one hand

**Comment by LTenhet** [comment]
Need to create Hostile Imperials and Hostile Republic forces for Plots.

**Comment by LTenhet** [comment]
Imperial Elite helmet is not in line with current equipment

**Comment by LTenhet** [comment]
Jedi Master Shara? has a person instead of a cat tail
Revenants have people instead of whatever bony dragon tail they had.

**Comment by LTenhet** [comment]
Fix rolling d20's, it currently cuts off the 0 so it only rolls a d2.

**Comment by RedComet313** [comment]
Moving d2 check to bottom of script might solve this...

**Comment by RedComet313** [comment]
Might want to remove whatever it is that only counts the first 2 damage types on blasters

**Comment by RedComet313** [comment]
D100 roll is screwed too, does d10. Seems like the system is checking for D2 and D10 before it checks for D20 and D100

**Comment by LTenhet** [comment]
Need to create Heavy stormtrooper armor (Void Trooper) and Medium armor (Assault Trooper), and probably rebel equivalent.

**Comment by LTenhet** [comment]
The Defiance isn't on the Docking List
Rebels are still on Yavin IV, the Defiance, and The Odysseus and need to be updated to Republic

**Comment by RedComet313** [comment]
UPDATE 20 APRIL 2018:
*Boss credit rewards reworked
*Additional fix to some ranged NPCs giving off errors
*BH OOC guy now gives correct credit rewards in reference to new rewards scaling
*Reworked summons' stats
*Removed Granny Smith
*Reworked Beastmaster's prices
*Merto
*Geonosis (Dooku/Droids)
*Recruiters (Tanis Palace - Empire, Naboo Palace- Republic, Nar Shad Mando BH, Nar Shad Criminal, Serenno commons BH and Criminal)
*Reworked Merto
*Rancor CR increased
*Death Cult CR decreased (Very slightly, I'm on to you people)

20 April 2018 changes DM Side:
*No more mastercraft merchants
*"Overcharged" Blasters, not a new tier, but more damage/ less ammo capacity than Mk V (Try to keep these as special rewards for players that deserve them)
*Creatures - Custom -Half Elves- Hostile versions of Republic/Empire NPCs (No uniques) (Not too much variety)
*No longer need to assist players if they want gold for boss items, the OOC guy is working just fine (ALSO, updated boss gold rewards, check forums)


UPDATE 21 APRIL 2018:
*Some areas marked as no jumping
*Fixed doors on Serenno
*Helped the poor Krayt dragon from tripping on rocks
*Nerfed Grievious a bit
*Nerfed Geonosis Droids (A little)

**Comment by LTenhet** [comment]
Cut back on some of the Sith and Jedi lazing about.

**Comment by RedComet313** [comment]
Would be rad if someone could remove the restriction on ranged weapons, you can place as many damages as you want on them, but only 2 will count. It's part of the script in the TLJ_blaster or some sort of one like that. Tried to make it allow a 3rd but I couldn't get it to work. Having unlimited ammo in this instance counts as a damage, so if you have an unlimited ammo weapon you can only have one more damage type. Easy way to test is make a weapon with unlimited normal ammo and then 2 elemental damages (Fire/electrical)
